from __future__ import annotations

from pathlib import Path


REFERENCE_DATA_DIR = Path(__file__).resolve().with_name("reference_data")
REFERENCE_DATA_SOURCES_DIR = REFERENCE_DATA_DIR / "sources"
REFERENCE_DATA_GENERATED_DIR = REFERENCE_DATA_DIR / "generated"

BUNDLED_REFERENCE_DATABASE_PATH = REFERENCE_DATA_GENERATED_DIR / "reference_values.db"
BUNDLED_TAXON_FILE_PATH = REFERENCE_DATA_SOURCES_DIR / "taxon.txt"
BUNDLED_VERNACULAR_FILE_PATH = REFERENCE_DATA_SOURCES_DIR / "vernacularname.txt"
BUNDLED_INAT_VERNACULAR_CSV_PATH = REFERENCE_DATA_GENERATED_DIR / "vernacular_inat_11lang.csv"
BUNDLED_VERNACULAR_DB_PATH = REFERENCE_DATA_GENERATED_DIR / "vernacular_multilanguage.sqlite3"
BUNDLED_VERNACULAR_UNIFIED_DB_PATH = REFERENCE_DATA_GENERATED_DIR / "vernacular_multilanguage_unified.sqlite3"
BUNDLED_ARTPORTALEN_BIOTOPES_PATH = REFERENCE_DATA_GENERATED_DIR / "artportalen_biotopes_tree.json"
BUNDLED_ARTPORTALEN_SUBSTRATE_PATH = REFERENCE_DATA_GENERATED_DIR / "artportalen_substrate_tree.json"
BUNDLED_NIN2_BIOTOPES_PATH = REFERENCE_DATA_GENERATED_DIR / "nin2_biotopes_tree.json"
BUNDLED_SUBSTRATE_TREE_PATH = REFERENCE_DATA_GENERATED_DIR / "substrate_tree.json"
